---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Swagger T24 Customer Creation"
  description: "An API that uses a T24 core banking system for the Customer creation.\
    \ It will create Individual & Organization for Wholesale, Corporate & Personal\
    \ banking domain "
  termsOfService: "http://cts.com/"
  contact:
    name: "Cognizant IPM"
    email: "apiteam@swagger.io"
    url: "http://swagger.io"
  license:
    name: "Apache 2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost.swagger.io"
basePath: "/corebanking"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /customer/individual:
    post:
      description: "Creates a new customer of type individual or organization in the\
        \ core banking"
      operationId: "addIndividual"
      parameters:
      - name: "customer"
        in: "body"
        description: "Customer to add to the system"
        required: true
        schema:
          $ref: "#/definitions/InvolvedPartyReq"
      responses:
        200:
          description: "Customer Creation response"
          schema:
            $ref: "#/definitions/InvolvedPartyReq"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /customer/organization:
    post:
      description: "Creates a new customer of type individual or organization in the\
        \ core banking"
      operationId: "addOrganization"
      parameters:
      - name: "customer"
        in: "body"
        description: "Customer to add to the system"
        required: true
        schema:
          $ref: "#/definitions/InvolvedPartyReq"
      responses:
        200:
          description: "Customer Creation response"
          schema:
            $ref: "#/definitions/InvolvedPartyReq"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/Error"
definitions:
  InvolvedPartyReq:
    type: "object"
    allOf:
    - $ref: "#/definitions/InvolvedParty"
    - required:
      - "id"
      properties:
        id:
          type: "integer"
          format: "int64"
  InvolvedParty:
    type: "object"
    required:
    - "fullName"
    properties:
      shortName:
        type: "string"
      fullName:
        type: "string"
      sector:
        type: "string"
      language:
        type: "string"
      accountOfficer:
        type: "string"
      industry:
        type: "string"
      target:
        type: "string"
      nationality:
        type: "string"
      customerStatus:
        type: "string"
      residenceType:
        type: "string"
      street:
        type: "string"
      gender:
        type: "string"
      maritalStatus:
        type: "string"
      salutation:
        type: "string"
      contactPerson:
        type: "object"
        allOf:
        - $ref: "#/definitions/contactPerson"
      country:
        type: "string"
      incorporationDate:
        type: "string"
      nationalIdentifier:
        type: "object"
        allOf:
        - $ref: "#/definitions/documentIdentifier"
      legalIdentifier:
        type: "object"
        allOf:
        - $ref: "#/definitions/documentIdentifier"
      passport:
        type: "object"
        allOf:
        - $ref: "#/definitions/documentIdentifier"
      town:
        type: "string"
      visaIdentifier:
        type: "object"
        allOf:
        - $ref: "#/definitions/documentIdentifier"
      email:
        type: "string"
      communication:
        type: "object"
        allOf:
        - $ref: "#/definitions/communication"
      overseas:
        type: "object"
        allOf:
        - $ref: "#/definitions/overseas"
      partyRelation:
        type: "object"
        allOf:
        - $ref: "#/definitions/partyRelation"
      education:
        type: "string"
      profession:
        type: "string"
      salary:
        type: "object"
        allOf:
        - $ref: "#/definitions/salary"
      employeeCode:
        type: "string"
      companyName:
        type: "string"
      employedSince:
        type: "string"
      letterOfUndertaking:
        type: "string"
      reference:
        type: "object"
        allOf:
        - $ref: "#/definitions/reference"
      company:
        type: "string"
      telephone:
        type: "string"
      authority:
        type: "object"
        allOf:
        - $ref: "#/definitions/authority"
      groupIdName:
        type: "string"
      powerOfAttorny:
        type: "object"
        allOf:
        - $ref: "#/definitions/powerOfAttorny"
      inBankBadBoyList:
        type: "string"
      postingRestrict:
        type: "string"
      websiteAddress:
        type: "string"
      employeeId:
        type: "string"
      citizenship:
        type: "string"
      drivingLicense:
        type: "object"
        allOf:
        - $ref: "#/definitions/documentIdentifier"
      creditCard:
        type: "object"
        allOf:
        - $ref: "#/definitions/card"
      customerCategory:
        type: "string"
      hra:
        type: "string"
      owncar:
        type: "string"
      nearLandmark:
        type: "string"
      numberOfDependents:
        type: "string"
      otherBankLoan:
        type: "string"
      otherBankName:
        type: "string"
      description:
        type: "string"
      ownHouse:
        type: "string"
      placeOfBirth:
        type: "string"
      document:
        type: "object"
        allOf:
        - $ref: "#/definitions/documentIdentifier"
      mailAddressCountry:
        type: "string"
      statemtMode:
        type: "string"
      holdingLocation:
        type: "string"
      mailLocation:
        type: "string"
      supportingDocument:
        type: "string"
      tin:
        type: "object"
        allOf:
        - $ref: "#/definitions/tin"
      ssn:
        type: "string"
      kyc:
        type: "object"
        allOf:
        - $ref: "#/definitions/kyc"
      sourceOfIncome:
        type: "string"
      amiriDecree:
        type: "string"
      associatedArticle:
        type: "string"
      boardResolution:
        type: "string"
      commercialRegistration:
        type: "string"
      declareDecission:
        type: "string"
      faxIndemnity:
        type: "string"
      jointVentureAgreement:
        type: "string"
      memoAssociated:
        type: "string"
      partnershipAgreement:
        type: "string"
      signatureCards:
        type: "string"
      tradeLicense:
        type: "object"
        allOf:
        - $ref: "#/definitions/documentIdentifier"
      introductoryAccount:
        type: "object"
        allOf:
        - $ref: "#/definitions/account"
      amlSegment:
        type: "string"
      customerSegment:
        type: "string"
      dsaId:
        type: "string"
      forEmployeePermit:
        type: "string"
      NRIC:
        type: "object"
        allOf:
        - $ref: "#/definitions/NRIC"
      postCode:
        type: "string"
      subClass:
        type: "string"
      FATCA:
        type: "object"
        allOf:
        - $ref: "#/definitions/FATCA"
      risk:
        type: "object"
        allOf:
        - $ref: "#/definitions/risk"
      currency:
        type: "object"
        allOf:
        - $ref: "#/definitions/currency"
      prospectNote:
        type: "string"
      FWC:
        type: "object"
        allOf:
        - $ref: "#/definitions/FWC"
  contactPerson:
    type: "object"
    required:
    - "name"
    - "phoneNumber"
    properties:
      name:
        type: "string"
      phoneNumber:
        type: "string"
  documentIdentifier:
    type: "object"
    required:
    - "identifier"
    - "expiaryDate"
    properties:
      identifier:
        type: "string"
      expiaryDate:
        type: "string"
      identifierName:
        type: "string"
      holderName:
        type: "string"
      issuer:
        type: "string"
      issueDate:
        type: "string"
      copy:
        type: "string"
  communication:
    type: "object"
    required:
    - "communicationType"
    - "telephoneNumber"
    properties:
      communicationType:
        type: "string"
      telephoneNumber:
        type: "string"
      extension:
        type: "string"
  overseas:
    type: "object"
    properties:
      address:
        type: "object"
        allOf:
        - $ref: "#/definitions/address"
      country:
        type: "string"
      telephoneNumber:
        type: "string"
  address:
    type: "object"
    properties:
      buildingName:
        type: "string"
      streetName:
        type: "string"
      address:
        type: "string"
  account:
    type: "object"
    properties:
      accountName:
        type: "string"
      classification:
        type: "string"
      custometIdentifier:
        type: "string"
  NRIC:
    type: "object"
    properties:
      number:
        type: "string"
      expiaryDate:
        type: "string"
  FATCA:
    type: "object"
    properties:
      status:
        type: "string"
      reportable:
        type: "string"
  FWC:
    type: "object"
    properties:
      member:
        type: "string"
      eligibilityType:
        type: "string"
      remailingEligibility:
        type: "string"
      eligibilityDate:
        type: "string"
      waveChange:
        type: "string"
      graceCharge:
        type: "string"
      remainingCharge:
        type: "string"
  currency:
    type: "object"
    properties:
      validity:
        type: "string"
  risk:
    type: "object"
    properties:
      category:
        type: "string"
      agreement:
        type: "string"
  partyRelation:
    type: "object"
    properties:
      code:
        type: "string"
      customer:
        type: "string"
      reverseCode:
        type: "string"
  salary:
    type: "object"
    properties:
      amount:
        type: "string"
      transferAccount:
        type: "string"
      basicAmount:
        type: "string"
  reference:
    type: "object"
    properties:
      type:
        type: "string"
      pobox:
        type: "string"
  powerOfAttorny:
    type: "object"
    properties:
      address:
        type: "string"
      notorise:
        type: "string"
      name:
        type: "string"
  card:
    type: "object"
    properties:
      expiaryDate:
        type: "string"
      number:
        type: "string"
  authority:
    type: "object"
    properties:
      limit:
        type: "string"
      signatory:
        type: "string"
      type:
        type: "string"
      name:
        type: "string"
      borrowing:
        type: "string"
      expiary:
        type: "string"
  tin:
    type: "object"
    properties:
      number:
        type: "string"
      issuedBy:
        type: "string"
      type:
        type: "string"
  kyc:
    type: "object"
    properties:
      firstKYCdate:
        type: "string"
      date:
        type: "string"
      expiaryDate:
        type: "string"
      reversaldate:
        type: "string"
  other:
    type: "object"
    properties:
      creditcard:
        type: "object"
        allOf:
        - $ref: "#/definitions/card"
      bank:
        type: "string"
      nationality:
        type: "string"
      residenceCountry:
        type: "string"
  Error:
    type: "object"
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
